language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker run -d -p 127.0.0.1:80:4567 -t letusfly85/dynalite dynalite
  - npm install aws-sdk
  - node node/create-table.js

script:
  - sbt -Dtest.env=CI clean compile test
